### ISSUE TITLE
TODO Features

### ISSUE THREAD

**Issue by r3valkyrie** [r3valkyrie/vishnu#1]
DICE:
- [ ] Rolling dice

- [ ] Adding multiple dice rolls together

QUESTS:
- [ ] Support for Postgres

- [ ] Creating quests

- [ ] Ensuring only DMs can make quests

- [ ] Retrieving quest by ID

- [ ] Retrieving random quest by tier.

- [ ] Retrieving all/random quests by creator

- [ ] DMs mark quests as complete

- [ ] Format quests in a table

FORTUNE:
- [ ] Allow players to request a fortune from the bot once per day

- [ ] Store the fortune in the Postgres database

- [ ] Allow DMs to retrieve fortunes from the database by specifying usernames 

CHANNEL MANAGEMENT:
- [ ] Allow DMs to "rent" channels. The bot will automatically add them to a group with appropriate permissions for that channel

- [ ] Allow DMs to invite players by Discord handle. The bot will automatically add them to a group with appropriate permissions for that channel.

- [ ] When a channel is rented, an expiration time will be set (in minutes). When this time expires, everyone is removed from the groups, kicked from the voice channel, and the text channel is cleared of all messages.
